name: Build CV
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: template.tex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV-PDF
          path: template.pdf
      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag_name: latest
          name: Latest CV
          files: template.pdf
          body: "Ultima versione generata automaticamente dal ramo main."
